// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for TemperatureResponseStatus.
const (
	Critical TemperatureResponseStatus = "critical"
	Normal   TemperatureResponseStatus = "normal"
	Offline  TemperatureResponseStatus = "offline"
	Warning  TemperatureResponseStatus = "warning"
)

// ErrorResponse Error response object
type ErrorResponse struct {
	// Code ErrorCode
	Code int `json:"code"`

	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// TemperatureResponse Temperature reading from sensor
type TemperatureResponse struct {
	// Description Additional description or notes
	Description string `json:"description"`

	// Location Physical location of the sensor
	Location string `json:"location"`

	// SensorId Unique identifier of the sensor
	SensorId string `json:"sensor_id"`

	// SensorType Type or model of the sensor
	SensorType string `json:"sensor_type"`

	// Status Status of the temperature reading
	Status TemperatureResponseStatus `json:"status"`

	// Timestamp Time when temperature was recorded
	Timestamp time.Time `json:"timestamp"`

	// Unit Unit of measurement (Celsius, Fahrenheit, etc.)
	Unit string `json:"unit"`

	// Value Temperature value
	Value float64 `json:"value"`
}

// TemperatureResponseStatus Status of the temperature reading
type TemperatureResponseStatus string

// Location defines model for location.
type Location = string

// Sensor defines model for sensor.
type Sensor = string

// TemperatureByLocationParams defines parameters for TemperatureByLocation.
type TemperatureByLocationParams struct {
	// Location location of sensor
	Location Location `form:"location" json:"location"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Temperature by location
	// (GET /temperature)
	TemperatureByLocation(w http.ResponseWriter, r *http.Request, params TemperatureByLocationParams)
	// Get Temperature by sensor
	// (GET /temperature/{sensor})
	TemperatureBySensor(w http.ResponseWriter, r *http.Request, sensor Sensor)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get Temperature by location
// (GET /temperature)
func (_ Unimplemented) TemperatureByLocation(w http.ResponseWriter, r *http.Request, params TemperatureByLocationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Temperature by sensor
// (GET /temperature/{sensor})
func (_ Unimplemented) TemperatureBySensor(w http.ResponseWriter, r *http.Request, sensor Sensor) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// TemperatureByLocation operation middleware
func (siw *ServerInterfaceWrapper) TemperatureByLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params TemperatureByLocationParams

	// ------------- Required query parameter "location" -------------

	if paramValue := r.URL.Query().Get("location"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "location"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "location", r.URL.Query(), &params.Location)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "location", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TemperatureByLocation(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TemperatureBySensor operation middleware
func (siw *ServerInterfaceWrapper) TemperatureBySensor(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sensor" -------------
	var sensor Sensor

	err = runtime.BindStyledParameterWithOptions("simple", "sensor", chi.URLParam(r, "sensor"), &sensor, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sensor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TemperatureBySensor(w, r, sensor)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/temperature", wrapper.TemperatureByLocation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/temperature/{sensor}", wrapper.TemperatureBySensor)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xW32/bNhD+V4jbHjaAsWUnAQa/rV03FMiKoU5fVhQDI51stiKpHE/xjED/+0D9sKhJ",
	"cTogLwP6ZvGO99199/HOj5A6UzqLlj1sHqFUpAwyUvNVuFSxdjb8ztCnpMv282QRLhcerXcEEnSw3FdI",
	"R5BglcHIESQQ3leaMIMNU4USfLpHo0JsPpbB1zNpu4O6ltDFnOC250JnPVypeD+gnVL5eqy6NzYVvyFy",
	"9B596azHKXxjFtTZhbv7jCmDhJJcicQamyCpy566+zqYZJ+Etow7JKglZMhKF3567ecs0+GnKgQ26L2n",
	"BPxbmbIIgd65rgsid5XNhGLRE78RN/pB251475wZoPv6JRj0Xu2eLLY3x3A3ffet4xZxGriOm/Cx5WQA",
	"k8DaoGdlSvh0utvxWUu4RVMiKa4In+5G5CQIVRaqzMmZQZHjvoxun+E5MghHoUgc0/270lbkhXPU025R",
	"kThom7nDHMdPP6Q/9kevU1WI+EXxHocaItrPN7K98ZfOpigfrL6vUOgMLetcI51B2b55t71IktUZiPZ8",
	"0o5jiYEv4zIszgD8sl399GqdzMZnxdXMI9g2531MnvY9ANjKBKVZR0YVIOGgyLamlDQHkkGCy/NCWwyi",
	"GzI6XZkkNKh0Wq42KA57tKN8DsoLwtRRhtmo6nWyvrpIVher69vV1eYy2STJnyAhD9AMG8gU40WAm0uj",
	"sppnu8qBE4PKV4QGLYsfXmPhdeWl+FXtCe0eNUuBnC5+HKXTuc2BPaiieua1tS5RvPXl4jouxlV3RVSJ",
	"rcxdmHP/Ggp9mKa8mGwZ741OFLHAx0qUo0yn4yTAapu7GV0hPegURe5IMKn0S3hfcTu1FZnOc6TAbZ9T",
	"w5rmhseYlds+QhcWJDwg+RZqtUgWSaDXlWhVqWEDl4tkcRmmlOJ9I/plBB2+d9h03TVn2tm32Rjx1fFm",
	"oCle3R8f4XvCHDbw3XJY8MvBZXnit/4UetKO2CaJdZK0S8wy2gZflWWhW/flZ99OsWGhzgF1G3U5N8ab",
	"djwnrVrCVXL1YnmM1/pMBh/sF+sOVgy0SLh+QSKeTeCtZaSwfHpJNjfa/0KVMYqOsIHfkEXM1d0xSriW",
	"I/0sH9snUn+dkLanlfmfZNSN928i+l+LqO9iXdf/BAAA//+CXtkbEQwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
